#lib.loc = "/scratch/user/hcchung/Rpackages/"
#install.packages("ape",lib= lib.loc, dependencies=TRUE)
#install.packages("phytools",lib= lib.loc, dependencies=TRUE)
#install.packages("phylobase",lib=lib.loc, dependencies=TRUE)
#install.packages("text2vec",lib=lib.loc, dependencies=TRUE)
#install.packages("ppcor",lib=lib.loc, dependencies=TRUE)
#install.packages("huge",lib=lib.loc, dependencies=TRUE)
#install.packages("igraph",lib=lib.loc, dependencies=TRUE)
#install.packages("BDgraph",lib=lib.loc, dependencies=TRUE)
#install.packages("gridExtra",lib=lib.loc, dependencies=TRUE)
#library(devtools)
#install_github("zdk123/SpiecEasi",lib= "/scratch/user/hcchung/R_LIBS_USER/4.0.3-foss-2020a-recommended-mt/", dependencies=TRUE)
#install.packages("spdep",lib=lib.loc, dependencies=TRUE)
#install.packages("rstan",lib=lib.loc, dependencies=TRUE)
#install.packages("rstan", lib = "/scratch/user/hcchung/Rpackages/", repos = "https://cloud.r-project.org/", dependencies = TRUE)
#Sys.setenv(DOWNLOAD_STATIC_LIBV8=1)
#install.packages("V8", lib = "/scratch/user/hcchung/Rpackages/")

#library(mvtnorm)
#library(tmvtnorm)
#library(TruncatedNormal)
library(boot)
library(matrixcalc)
library(Matrix)
#library(emulator)
library(numDeriv)
library(ape)
library(rstan)
library(loo)
rstan_options(auto_write = TRUE)
options(mc.cores = 4 )




